"""Browser-captured membership of the wiki's ``Category:Rare Loot List items``.

STOPGAP, on the same footing as :mod:`ddo_data.game_data.raid_quests`. The
authoritative source is the wiki category itself, which ``wiki/scraper.py``
would walk like any other — but ddowiki.com sits behind an AWS WAF JavaScript
challenge that answers every non-browser client with HTTP 202 and an empty body
(see docs/ddowiki-api.md, re-confirmed 2026-07-29). A real browser passes the
challenge via top-level navigation, so this list was read out of one by hand on
2026-07-28 and pasted here.

Delete this module — and ``collect_rare_loot_names``'s use of it — once
``iter_category_members`` can reach the category again.

Why it is needed at all when the item infobox has a ``| rare =`` field: the
field names only 122 items, 119 of which are also in this 216-member category.
The category is the broader source and the field adds 3 names of its own, so
``collect_rare_loot_names`` unions the two and reports the disagreement rather
than silently preferring one.

Note on shape: many of these names are Lunar/Solar Gems, which the pipeline
stores in ``augments`` rather than ``items`` — 139 of the 219 reconciled names
match ``items``, 79 match ``augments``, hence ``augments.is_rare`` alongside
``items.rarity``. Names matching neither are counted in the reconciliation
report instead of vanishing.
"""

from __future__ import annotations

RARE_LOOT_ITEMS: tuple[str, ...] = (
    "Buckle of Secrets",
    "Buckler of the Golden Age",
    "Chilling Sash of Tailara",
    "Climber's Remembrance",
    "Cloak of the Artblade",
    "Cloak of the Crownblade",
    "Cloak of the Warblade",
    "Contraption Keyring",
    "Crackling Sash of Savaran",
    "Crisis Claw",
    "Deadmonger Gang's Signet",
    "Dhovras' Armlet",
    "Docent of the Artblade",
    "Docent of the Crownblade",
    "Docent of the Warblade",
    "Downcast Armor",
    "Downcast Brawler's Garb",
    "Downcast Docent",
    "Downcast Gambeson",
    "Downcast Robe",
    "Downcast Vest",
    "Echo of the Artblade",
    "Echo of the Crownblade",
    "Echo of the Warblade",
    "Epic Crisis Claw",
    "Epic Dhovras' Armlet",
    "Fraying Sash of Phinorae",
    "Fried Fish Stick",
    "Frozen Contraption",
    "Frozen Fish Stick",
    "Goggles of the Frozen Night",
    "Golden Souvenir Coin",
    "Hands of Waste",
    "Heartshard",
    "Heavy Armor of the Artblade",
    "Heavy Armor of the Crownblade",
    "Heavy Armor of the Warblade",
    "Helm of the Artblade",
    "Helm of the Crownblade",
    "Helm of the Warblade",
    "Icewalkers",
    "Large Shield of the Golden Age",
    "Legendary Buckle of Secrets",
    "Legendary Buckler of the Golden Age",
    "Legendary Chilling Sash of Tailara",
    "Legendary Climber's Remembrance",
    "Legendary Cloak of the Artblade",
    "Legendary Cloak of the Crownblade",
    "Legendary Cloak of the Warblade",
    "Legendary Contraption Keyring",
    "Legendary Crackling Sash of Savaran",
    "Legendary Deadmonger Gang's Signet",
    "Legendary Docent of the Artblade",
    "Legendary Docent of the Crownblade",
    "Legendary Docent of the Warblade",
    "Legendary Downcast Armor",
    "Legendary Downcast Brawler's Garb",
    "Legendary Downcast Docent",
    "Legendary Downcast Gambeson",
    "Legendary Downcast Robe",
    "Legendary Downcast Vest",
    "Legendary Echo of the Artblade",
    "Legendary Echo of the Crownblade",
    "Legendary Echo of the Warblade",
    "Legendary Fraying Sash of Phinorae",
    "Legendary Fried Fish Stick",
    "Legendary Frozen Contraption",
    "Legendary Frozen Fish Stick",
    "Legendary Goggles of the Frozen Night",
    "Legendary Golden Souvenir Coin",
    "Legendary Hands of Waste",
    "Legendary Heartshard",
    "Legendary Heavy Armor of the Artblade",
    "Legendary Heavy Armor of the Crownblade",
    "Legendary Heavy Armor of the Warblade",
    "Legendary Helm of the Artblade",
    "Legendary Helm of the Crownblade",
    "Legendary Helm of the Warblade",
    "Legendary Icewalkers",
    "Legendary Large Shield of the Golden Age",
    "Legendary Lesser Oblivion",
    "Legendary Light Armor of the Artblade",
    "Legendary Light Armor of the Crownblade",
    "Legendary Light Armor of the Warblade",
    "Legendary Medium Armor of the Artblade",
    "Legendary Medium Armor of the Crownblade",
    "Legendary Medium Armor of the Warblade",
    "Legendary Moonlight Slinger",
    "Legendary Nightbringer's Wake",
    "Legendary Outfit of the Artblade",
    "Legendary Outfit of the Crownblade",
    "Legendary Outfit of the Warblade",
    "Legendary Poniard of Pain",
    "Legendary Robe of the Artblade",
    "Legendary Robe of the Crownblade",
    "Legendary Robe of the Warblade",
    "Legendary Rune Arm of Nature's Wrath",
    "Legendary Sanguine Sash of Estelar",
    "Legendary Selune's Favor",
    "Legendary Selune's Light",
    "Legendary Small Shield of the Golden Age",
    "Legendary Tower Shield of the Golden Age",
    "Legendary Toxic Sash of Drysvayla",
    "Legendary Wintery Wrappings",
    "Lesser Oblivion",
    "Light Armor of the Artblade",
    "Light Armor of the Crownblade",
    "Light Armor of the Warblade",
    "Lunar Gem of Abjuration (Heroic)",
    "Lunar Gem of Abjuration (Legendary)",
    "Lunar Gem of Blast Dice (Heroic)",
    "Lunar Gem of Blast Dice (Legendary)",
    "Lunar Gem of Disable Device and Open Lock (Heroic)",
    "Lunar Gem of Disable Device and Open Lock (Legendary)",
    "Lunar Gem of Enchantment (Heroic)",
    "Lunar Gem of Enchantment (Legendary)",
    "Lunar Gem of Haggle and Perform (Heroic)",
    "Lunar Gem of Haggle and Perform (Legendary)",
    "Lunar Gem of Illusion (Heroic)",
    "Lunar Gem of Illusion (Legendary)",
    "Lunar Gem of Jump and Swim (Heroic)",
    "Lunar Gem of Jump and Swim (Legendary)",
    "Lunar Gem of Linguistics (Heroic)",
    "Lunar Gem of Linguistics (Legendary)",
    "Lunar Gem of Pact Dice (Heroic)",
    "Lunar Gem of Pact Dice (Legendary)",
    "Lunar Gem of Search and Spot (Heroic)",
    "Lunar Gem of Search and Spot (Legendary)",
    "Lunar Gem of Transmutation (Heroic)",
    "Lunar Gem of Transmutation (Legendary)",
    "Medium Armor of the Artblade",
    "Medium Armor of the Crownblade",
    "Medium Armor of the Warblade",
    "Moonlight Slinger",
    "Nightbringer's Wake",
    "Outfit of the Artblade",
    "Outfit of the Crownblade",
    "Outfit of the Warblade",
    "Poniard of Pain",
    "Robe of the Artblade",
    "Robe of the Crownblade",
    "Robe of the Warblade",
    "Rune Arm of Nature's Wrath",
    "Sanguine Sash of Estelar",
    "Selune's Favor",
    "Selune's Light",
    "Small Shield of the Golden Age",
    "Solar Gem of Abjuration (Heroic)",
    "Solar Gem of Abjuration (Legendary)",
    "Solar Gem of Arcane Endurance (Heroic)",
    "Solar Gem of Arcane Endurance (Legendary)",
    "Solar Gem of Attack (Heroic)",
    "Solar Gem of Attack (Legendary)",
    "Solar Gem of Blast Dice (Heroic)",
    "Solar Gem of Blast Dice (Legendary)",
    "Solar Gem of Conjuration (Heroic)",
    "Solar Gem of Conjuration (Legendary)",
    "Solar Gem of Critical Confirmation (Heroic)",
    "Solar Gem of Critical Confirmation (Legendary)",
    "Solar Gem of Cruelty (Heroic)",
    "Solar Gem of Cruelty (Legendary)",
    "Solar Gem of Damage (Heroic)",
    "Solar Gem of Damage (Legendary)",
    "Solar Gem of Dodge Cap (Heroic)",
    "Solar Gem of Dodge Cap (Legendary)",
    "Solar Gem of Elemental Absorption (Heroic)",
    "Solar Gem of Elemental Absorption (Legendary)",
    "Solar Gem of Enchantment (Heroic)",
    "Solar Gem of Enchantment (Legendary)",
    "Solar Gem of Enduring (Heroic)",
    "Solar Gem of Enduring (Legendary)",
    "Solar Gem of Evocation (Heroic)",
    "Solar Gem of Evocation (Legendary)",
    "Solar Gem of Force Absorption (Heroic)",
    "Solar Gem of Force Absorption (Legendary)",
    "Solar Gem of Fortification Bypass (Epic)",
    "Solar Gem of Fortification Bypass (Heroic)",
    "Solar Gem of Fortification Bypass (Legendary)",
    "Solar Gem of Illusion (Heroic)",
    "Solar Gem of Illusion (Legendary)",
    "Solar Gem of Imbuement (Epic)",
    "Solar Gem of Imbuement (Heroic)",
    "Solar Gem of Imbuement (Legendary)",
    "Solar Gem of Linguistics (Heroic)",
    "Solar Gem of Linguistics (Legendary)",
    "Solar Gem of MRR Cap (Heroic)",
    "Solar Gem of MRR Cap (Legendary)",
    "Solar Gem of Necromancy (Heroic)",
    "Solar Gem of Necromancy (Legendary)",
    "Solar Gem of Pact Dice (Heroic)",
    "Solar Gem of Pact Dice (Legendary)",
    "Solar Gem of Rune Arm DCs (Heroic)",
    "Solar Gem of Rune Arm DCs (Legendary)",
    "Solar Gem of Sneak Attack Dice (Heroic)",
    "Solar Gem of Sneak Attack Dice (Legendary)",
    "Solar Gem of Spell Critical Chance (Epic)",
    "Solar Gem of Spell Critical Chance (Heroic)",
    "Solar Gem of Spell Critical Chance (Legendary)",
    "Solar Gem of Strikethrough (Epic)",
    "Solar Gem of Strikethrough (Heroic)",
    "Solar Gem of Strikethrough (Legendary)",
    "Solar Gem of Swift Charging (Heroic)",
    "Solar Gem of Swift Charging (Legendary)",
    "Solar Gem of Transmutation (Heroic)",
    "Solar Gem of Transmutation (Legendary)",
    "The Autumn Equinox",
    "The Spring Equinox",
    "The Summer Solstice",
    "The Theurgy of Autumn",
    "The Theurgy of Spring",
    "The Theurgy of Summer",
    "The Theurgy of Winter",
    "The Winter Solstice",
    "Tower Shield of the Golden Age",
    "Toxic Sash of Drysvayla",
    "Wintery Wrappings",
)
